### ISSUE TITLE
detect return of constant

### ISSUE THREAD

**Issue by mingo-x** [at15/scala-linter#4]
```
def localUnused: Int = {
    val x = 2
    val y = 1
    3
  }
```

when return is constant, can't detect dead code

```
def localUnused: Int = {
    val x = 2
    val y = 1
    3+1
  }
```

if we change the return to an operation, dead code can be detected

**Comment by at15** [comment]
@mingo-x when return value is a constant, the code above the return value is not in the ast.

run the flowing code in repel or worksheet

```
import scala.reflect.runtime.universe._

val expr = reify {
  def s():Int = {
    val a = 2
    3
  }
}

show(expr.tree)
showRaw(expr.tree)
expr.tree.pos
```

the result is 

```
def s(): Int = 3;
  ()

Block(List(DefDef(Modifiers(), TermName("s"), List(), List(List()), Ident(scala.Int), Literal(Constant(3)))), Literal(Constant(())))

reflect.runtime.universe.Position = NoPosition
```

meaning when parsing, these code are already eliminated, possible approaches are
- warn all the methods that return a constant value. (I think there is already some scalac option or linter doing this)
- find the original code before parse and warn user, but tree.pos says `NoPosition` maybe it's because of I am using worksheet ....

**Comment by at15** [comment]
The NoPosition is because of using worksheet, so no source file. And see #6 for more detail
